name: Build and publish Site image

on:
  push:
    branches: [ main ]
    paths-ignore:
      - .github/**/*
      - devenv*
      - README.md
  workflow_dispatch:

env:
  REGISTRY: git.iw2tryhard.dev 
  IMAGE_NAME: ${{ forgejo.repository }}

jobs:
  build:
    runs-on: native-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: itscrystalline 
          password: ${{ secrets.DOCKER_PUSH }}

      - name: Build
        run: |
          nix build .\#docker -L 2>&1
          ./result | docker image load

      - name: Load and tag image
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          LABELS: ${{ steps.meta.outputs.labels }}
          SHA_HASH: ${{ forgejo.sha }}  
        run: |
          sha_short="${SHA_HASH:0:7}"  
          docker tag iw2tryhard-dev:latest $REGISTRY/$IMAGE_NAME:latest
          docker tag iw2tryhard-dev:latest $REGISTRY/$IMAGE_NAME:$sha_short
          docker push $REGISTRY/$IMAGE_NAME:latest
          docker push $REGISTRY/$IMAGE_NAME:$sha_short


